[package]
name = "live_clone_rust"
version = "0.1.0"
edition = "2021"

[dependencies]
iced = { version = "0.10", features = ["tokio"] }
rodio = "0.17"
tokio = { version = "1.0", features = ["time"] }
